#include "gpio.h"

void startClk_gpioA(void){
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
}

void startClk_gpioB(void){
	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;
}

void startClk_gpioC(void){
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;
}

void startClk_gpioD(void){
	RCC->APB2ENR |= RCC_APB2ENR_IOPDEN;
}

void setupGPIO(void){
	//----------MODE----------
	//Uncomment the following to set the pin to an output (default: input)
	//*****GPIOA*****
	//GPIOA->CRL |= GPIO_CRL_MODE0;
	//GPIOA->CRL |= GPIO_CRL_MODE1;
	//GPIOA->CRL |= GPIO_CRL_MODE2;
	//GPIOA->CRL |= GPIO_CRL_MODE3;
	//GPIOA->CRL |= GPIO_CRL_MODE4;
	GPIOA->CRL |= GPIO_CRL_MODE5;
	GPIOA->CRL |= GPIO_CRL_MODE6;
	GPIOA->CRL |= GPIO_CRL_MODE7;
	//GPIOA->CRH |= GPIO_CRH_MODE8;
	//GPIOA->CRH |= GPIO_CRH_MODE9;
	//GPIOA->CRH |= GPIO_CRH_MODE10;
	GPIOA->CRH |= GPIO_CRH_MODE11;
	GPIOA->CRH |= GPIO_CRH_MODE12;
	//GPIOA->CRH |= GPIO_CRH_MODE13;
	//GPIOA->CRH |= GPIO_CRH_MODE14;
	//GPIOA->CRH |= GPIO_CRH_MODE15;
	//*****GPIOB*****
	GPIOB->CRL |= GPIO_CRL_MODE0;
	GPIOB->CRL |= GPIO_CRL_MODE1;
	//GPIOB->CRL |= GPIO_CRL_MODE2;
	//GPIOB->CRL |= GPIO_CRL_MODE3;
	//GPIOB->CRL |= GPIO_CRL_MODE4;
	GPIOB->CRL |= GPIO_CRL_MODE5;
	GPIOB->CRL |= GPIO_CRL_MODE6;
	GPIOB->CRL |= GPIO_CRL_MODE7;
	GPIOB->CRH |= GPIO_CRH_MODE8;
	//GPIOB->CRH |= GPIO_CRH_MODE9;
	GPIOB->CRH |= GPIO_CRH_MODE10;
	GPIOB->CRH |= GPIO_CRH_MODE11;
	GPIOB->CRH |= GPIO_CRH_MODE12;
	GPIOB->CRH |= GPIO_CRH_MODE13;
	GPIOB->CRH |= GPIO_CRH_MODE14;
	GPIOB->CRH |= GPIO_CRH_MODE15;
	//*****GPIOC*****
	//GPIOC->CRL |= GPIO_CRL_MODE0;
	//GPIOC->CRL |= GPIO_CRL_MODE1;
	//GPIOC->CRL |= GPIO_CRL_MODE2;
	//GPIOC->CRL |= GPIO_CRL_MODE3;
	//GPIOC->CRL |= GPIO_CRL_MODE4;
	//GPIOC->CRL |= GPIO_CRL_MODE5;
	//GPIOC->CRL |= GPIO_CRL_MODE6;
	//GPIOC->CRL |= GPIO_CRL_MODE7;
	//GPIOC->CRH |= GPIO_CRH_MODE8;
	//GPIOC->CRH |= GPIO_CRH_MODE9;
	//GPIOC->CRH |= GPIO_CRH_MODE10;
	//GPIOC->CRH |= GPIO_CRH_MODE11;
	//GPIOC->CRH |= GPIO_CRH_MODE12;
	//GPIOC->CRH |= GPIO_CRH_MODE13;
	//GPIOC->CRH |= GPIO_CRH_MODE14;
	//GPIOC->CRH |= GPIO_CRH_MODE15;
	//*****GPIOD*****
	//GPIOD->CRL |= GPIO_CRL_MODE0;
	//GPIOD->CRL |= GPIO_CRL_MODE1;
	//GPIOD->CRL |= GPIO_CRL_MODE2;
	//GPIOD->CRL |= GPIO_CRL_MODE3;
	//GPIOD->CRL |= GPIO_CRL_MODE4;
	//GPIOD->CRL |= GPIO_CRL_MODE5;
	//GPIOD->CRL |= GPIO_CRL_MODE6;
	//GPIOD->CRL |= GPIO_CRL_MODE7;
	//GPIOD->CRH |= GPIO_CRH_MODE8;
	//GPIOD->CRH |= GPIO_CRH_MODE9;
	//GPIOD->CRH |= GPIO_CRH_MODE10;
	//GPIOD->CRH |= GPIO_CRH_MODE11;
	//GPIOD->CRH |= GPIO_CRH_MODE12;
	//GPIOD->CRH |= GPIO_CRH_MODE13;
	//GPIOD->CRH |= GPIO_CRH_MODE14;
	//GPIOD->CRH |= GPIO_CRH_MODE15;
	
	
	//----------CNF----------
	//                                               INPUT MODE        OUTPUT MODE
	//Uncomment the following to set the pin to 00: (analog          | push-pull    )
	//*****GPIOA*****
	GPIOA->CRL &= ~GPIO_CRL_CNF0;
	//GPIOA->CRL &= ~GPIO_CRL_CNF1;
	//GPIOA->CRL &= ~GPIO_CRL_CNF2;
	//GPIOA->CRL &= ~GPIO_CRL_CNF3;
	//GPIOA->CRL &= ~GPIO_CRL_CNF4;
	GPIOA->CRL &= ~GPIO_CRL_CNF5;
	//GPIOA->CRL &= ~GPIO_CRL_CNF6;
	//GPIOA->CRL &= ~GPIO_CRL_CNF7;
	//GPIOA->CRH &= ~GPIO_CRH_CNF8;
	//GPIOA->CRH &= ~GPIO_CRH_CNF9;
	//GPIOA->CRH &= ~GPIO_CRH_CNF10;
	GPIOA->CRH &= ~GPIO_CRH_CNF11;
	GPIOA->CRH &= ~GPIO_CRH_CNF12;
	//GPIOA->CRH &= ~GPIO_CRH_CNF13;
	//GPIOA->CRH &= ~GPIO_CRH_CNF14;
	//GPIOA->CRH &= ~GPIO_CRH_CNF15;
	//*****GPIOB*****
	//GPIOB->CRL &= ~GPIO_CRL_CNF0;
	//GPIOB->CRL &= ~GPIO_CRL_CNF1;
	//GPIOB->CRL &= ~GPIO_CRL_CNF2;
	//GPIOB->CRL &= ~GPIO_CRL_CNF3;
	//GPIOB->CRL &= ~GPIO_CRL_CNF4;
	GPIOB->CRL &= ~GPIO_CRL_CNF5;
	//GPIOB->CRL &= ~GPIO_CRL_CNF6;
	//GPIOB->CRL &= ~GPIO_CRL_CNF7;
	GPIOB->CRH &= ~GPIO_CRH_CNF8;
	//GPIOB->CRH &= ~GPIO_CRH_CNF9;
	GPIOB->CRH &= ~GPIO_CRH_CNF10;
	GPIOB->CRH &= ~GPIO_CRH_CNF11;
	GPIOB->CRH &= ~GPIO_CRH_CNF12;
	GPIOB->CRH &= ~GPIO_CRH_CNF13;
	GPIOB->CRH &= ~GPIO_CRH_CNF14;
	GPIOB->CRH &= ~GPIO_CRH_CNF15;
	//*****GPIOC*****
	//GPIOC->CRL &= ~GPIO_CRL_CNF0;
	//GPIOC->CRL &= ~GPIO_CRL_CNF1;
	//GPIOC->CRL &= ~GPIO_CRL_CNF2;
	//GPIOC->CRL &= ~GPIO_CRL_CNF3;
	//GPIOC->CRL &= ~GPIO_CRL_CNF4;
	//GPIOC->CRL &= ~GPIO_CRL_CNF5;
	//GPIOC->CRL &= ~GPIO_CRL_CNF6;
	//GPIOC->CRL &= ~GPIO_CRL_CNF7;
	//GPIOC->CRH &= ~GPIO_CRH_CNF8;
	//GPIOC->CRH &= ~GPIO_CRH_CNF9;
	//GPIOC->CRH &= ~GPIO_CRH_CNF10;
	//GPIOC->CRH &= ~GPIO_CRH_CNF11;
	//GPIOC->CRH &= ~GPIO_CRH_CNF12;
	//GPIOC->CRH &= ~GPIO_CRH_CNF13;
	//GPIOC->CRH &= ~GPIO_CRH_CNF14;
	//GPIOC->CRH &= ~GPIO_CRH_CNF15;
	//*****GPIOD*****
	//GPIOD->CRL &= ~GPIO_CRL_CNF0;
	//GPIOD->CRL &= ~GPIO_CRL_CNF1;
	//GPIOD->CRL &= ~GPIO_CRL_CNF2;
	//GPIOD->CRL &= ~GPIO_CRL_CNF3;
	//GPIOD->CRL &= ~GPIO_CRL_CNF4;
	//GPIOD->CRL &= ~GPIO_CRL_CNF5;
	//GPIOD->CRL &= ~GPIO_CRL_CNF6;
	//GPIOD->CRL &= ~GPIO_CRL_CNF7;
	//GPIOD->CRH &= ~GPIO_CRH_CNF8;
	//GPIOD->CRH &= ~GPIO_CRH_CNF9;
	//GPIOD->CRH &= ~GPIO_CRH_CNF10;
	//GPIOD->CRH &= ~GPIO_CRH_CNF11;
	//GPIOD->CRH &= ~GPIO_CRH_CNF12;
	//GPIOD->CRH &= ~GPIO_CRH_CNF13;
	//GPIOD->CRH &= ~GPIO_CRH_CNF14;
	//GPIOD->CRH &= ~GPIO_CRH_CNF15;
	//Uncomment the following to set the pin to 01: (floating        | open-drain   ) DEFAULT - NO NEED TO UNCOMMENT
	//*****GPIOA*****
	//GPIOA->CRL &= ~GPIO_CRL_CNF0;  GPIOA->CRL |= GPIO_CRL_CNF0_0;	
	//GPIOA->CRL &= ~GPIO_CRL_CNF1;  GPIOA->CRL |= GPIO_CRL_CNF1_0;	
	//GPIOA->CRL &= ~GPIO_CRL_CNF2;  GPIOA->CRL |= GPIO_CRL_CNF2_0;	
	//GPIOA->CRL &= ~GPIO_CRL_CNF3;  GPIOA->CRL |= GPIO_CRL_CNF3_0;	
	//GPIOA->CRL &= ~GPIO_CRL_CNF4;  GPIOA->CRL |= GPIO_CRL_CNF4_0;	
	//GPIOA->CRL &= ~GPIO_CRL_CNF5;  GPIOA->CRL |= GPIO_CRL_CNF5_0;	
	//GPIOA->CRL &= ~GPIO_CRL_CNF6;  GPIOA->CRL |= GPIO_CRL_CNF6_0;	
	//GPIOA->CRL &= ~GPIO_CRL_CNF7;  GPIOA->CRL |= GPIO_CRL_CNF7_0;
	//GPIOA->CRH &= ~GPIO_CRH_CNF8;  GPIOA->CRH |= GPIO_CRH_CNF8_0;		
	//GPIOA->CRH &= ~GPIO_CRH_CNF9;  GPIOA->CRH |= GPIO_CRH_CNF9_0;	
	//GPIOA->CRH &= ~GPIO_CRH_CNF10; GPIOA->CRH |= GPIO_CRH_CNF10_0;	
	//GPIOA->CRH &= ~GPIO_CRH_CNF11; GPIOA->CRH |= GPIO_CRH_CNF11_0;	
	//GPIOA->CRH &= ~GPIO_CRH_CNF12; GPIOA->CRH |= GPIO_CRH_CNF12_0;	
	//GPIOA->CRH &= ~GPIO_CRH_CNF13; GPIOA->CRH |= GPIO_CRH_CNF13_0;	
	//GPIOA->CRH &= ~GPIO_CRH_CNF14; GPIOA->CRH |= GPIO_CRH_CNF14_0;	
	//GPIOA->CRH &= ~GPIO_CRH_CNF15; GPIOA->CRH |= GPIO_CRH_CNF15_0;	
	//*****GPIOB*****	
	//GPIOB->CRL &= ~GPIO_CRL_CNF0;  GPIOB->CRL |= GPIO_CRL_CNF0_0;	
	//GPIOB->CRL &= ~GPIO_CRL_CNF1;  GPIOB->CRL |= GPIO_CRL_CNF1_0;	
	//GPIOB->CRL &= ~GPIO_CRL_CNF2;  GPIOB->CRL |= GPIO_CRL_CNF2_0;	
	//GPIOB->CRL &= ~GPIO_CRL_CNF3;  GPIOB->CRL |= GPIO_CRL_CNF3_0;	
	//GPIOB->CRL &= ~GPIO_CRL_CNF4;  GPIOB->CRL |= GPIO_CRL_CNF4_0;	
	//GPIOB->CRL &= ~GPIO_CRL_CNF5;  GPIOB->CRL |= GPIO_CRL_CNF5_0;	
	//GPIOB->CRL &= ~GPIO_CRL_CNF6;  GPIOB->CRL |= GPIO_CRL_CNF6_0;	
	//GPIOB->CRL &= ~GPIO_CRL_CNF7;  GPIOB->CRL |= GPIO_CRL_CNF7_0;
	//GPIOB->CRH &= ~GPIO_CRH_CNF8;  GPIOB->CRH |= GPIO_CRH_CNF8_0;		
	//GPIOB->CRH &= ~GPIO_CRH_CNF9;  GPIOB->CRH |= GPIO_CRH_CNF9_0;	
	//GPIOB->CRH &= ~GPIO_CRH_CNF10; GPIOB->CRH |= GPIO_CRH_CNF10_0;	
	//GPIOB->CRH &= ~GPIO_CRH_CNF11; GPIOB->CRH |= GPIO_CRH_CNF11_0;	
	//GPIOB->CRH &= ~GPIO_CRH_CNF12; GPIOB->CRH |= GPIO_CRH_CNF12_0;	
	//GPIOB->CRH &= ~GPIO_CRH_CNF13; GPIOB->CRH |= GPIO_CRH_CNF13_0;	
	//GPIOB->CRH &= ~GPIO_CRH_CNF14; GPIOB->CRH |= GPIO_CRH_CNF14_0;	
	//GPIOB->CRH &= ~GPIO_CRH_CNF15; GPIOB->CRH |= GPIO_CRH_CNF15_0;	
	//*****GPIOC*****
	//GPIOC->CRL &= ~GPIO_CRL_CNF0;  GPIOC->CRL |= GPIO_CRL_CNF0_0;	
	//GPIOC->CRL &= ~GPIO_CRL_CNF1;  GPIOC->CRL |= GPIO_CRL_CNF1_0;	
	//GPIOC->CRL &= ~GPIO_CRL_CNF2;  GPIOC->CRL |= GPIO_CRL_CNF2_0;	
	//GPIOC->CRL &= ~GPIO_CRL_CNF3;  GPIOC->CRL |= GPIO_CRL_CNF3_0;	
	//GPIOC->CRL &= ~GPIO_CRL_CNF4;  GPIOC->CRL |= GPIO_CRL_CNF4_0;	
	//GPIOC->CRL &= ~GPIO_CRL_CNF5;  GPIOC->CRL |= GPIO_CRL_CNF5_0;	
	//GPIOC->CRL &= ~GPIO_CRL_CNF6;  GPIOC->CRL |= GPIO_CRL_CNF6_0;	
	//GPIOC->CRL &= ~GPIO_CRL_CNF7;  GPIOC->CRL |= GPIO_CRL_CNF7_0;
	//GPIOC->CRH &= ~GPIO_CRH_CNF8;  GPIOC->CRH |= GPIO_CRH_CNF8_0;		
	//GPIOC->CRH &= ~GPIO_CRH_CNF9;  GPIOC->CRH |= GPIO_CRH_CNF9_0;	
	//GPIOC->CRH &= ~GPIO_CRH_CNF10; GPIOC->CRH |= GPIO_CRH_CNF10_0;	
	//GPIOC->CRH &= ~GPIO_CRH_CNF11; GPIOC->CRH |= GPIO_CRH_CNF11_0;	
	//GPIOC->CRH &= ~GPIO_CRH_CNF12; GPIOC->CRH |= GPIO_CRH_CNF12_0;	
	//GPIOC->CRH &= ~GPIO_CRH_CNF13; GPIOC->CRH |= GPIO_CRH_CNF13_0;	
	//GPIOC->CRH &= ~GPIO_CRH_CNF14; GPIOC->CRH |= GPIO_CRH_CNF14_0;	
	//GPIOC->CRH &= ~GPIO_CRH_CNF15; GPIOC->CRH |= GPIO_CRH_CNF15_0;	
	//*****GPIOD*****
	//GPIOD->CRL &= ~GPIO_CRL_CNF0;  GPIOD->CRL |= GPIO_CRL_CNF0_0;	
	//GPIOD->CRL &= ~GPIO_CRL_CNF1;  GPIOD->CRL |= GPIO_CRL_CNF1_0;	
	//GPIOD->CRL &= ~GPIO_CRL_CNF2;  GPIOD->CRL |= GPIO_CRL_CNF2_0;	
	//GPIOD->CRL &= ~GPIO_CRL_CNF3;  GPIOD->CRL |= GPIO_CRL_CNF3_0;	
	//GPIOD->CRL &= ~GPIO_CRL_CNF4;  GPIOD->CRL |= GPIO_CRL_CNF4_0;	
	//GPIOD->CRL &= ~GPIO_CRL_CNF5;  GPIOD->CRL |= GPIO_CRL_CNF5_0;	
	//GPIOD->CRL &= ~GPIO_CRL_CNF6;  GPIOD->CRL |= GPIO_CRL_CNF6_0;	
	//GPIOD->CRL &= ~GPIO_CRL_CNF7;  GPIOD->CRL |= GPIO_CRL_CNF7_0;
	//GPIOD->CRH &= ~GPIO_CRH_CNF8;  GPIOD->CRH |= GPIO_CRH_CNF8_0;		
	//GPIOD->CRH &= ~GPIO_CRH_CNF9;  GPIOD->CRH |= GPIO_CRH_CNF9_0;	
	//GPIOD->CRH &= ~GPIO_CRH_CNF10; GPIOD->CRH |= GPIO_CRH_CNF10_0;	
	//GPIOD->CRH &= ~GPIO_CRH_CNF11; GPIOD->CRH |= GPIO_CRH_CNF11_0;	
	//GPIOD->CRH &= ~GPIO_CRH_CNF12; GPIOD->CRH |= GPIO_CRH_CNF12_0;	
	//GPIOD->CRH &= ~GPIO_CRH_CNF13; GPIOD->CRH |= GPIO_CRH_CNF13_0;	
	//GPIOD->CRH &= ~GPIO_CRH_CNF14; GPIOD->CRH |= GPIO_CRH_CNF14_0;	
	//GPIOD->CRH &= ~GPIO_CRH_CNF15; GPIOD->CRH |= GPIO_CRH_CNF15_0;	
	//Uncomment the following to set the pin to 10: (pull up/down    | af push-pull )
	//*****GPIOA*****
	//GPIOA->CRL &= ~GPIO_CRL_CNF0;  GPIOA->CRL |= GPIO_CRL_CNF0_1;	
	//GPIOA->CRL &= ~GPIO_CRL_CNF1;  GPIOA->CRL |= GPIO_CRL_CNF1_1;	
	//GPIOA->CRL &= ~GPIO_CRL_CNF2;  GPIOA->CRL |= GPIO_CRL_CNF2_1;	
	//GPIOA->CRL &= ~GPIO_CRL_CNF3;  GPIOA->CRL |= GPIO_CRL_CNF3_1;	
	//GPIOA->CRL &= ~GPIO_CRL_CNF4;  GPIOA->CRL |= GPIO_CRL_CNF4_1;	
	//GPIOA->CRL &= ~GPIO_CRL_CNF5;  GPIOA->CRL |= GPIO_CRL_CNF5_1;	
	GPIOA->CRL &= ~GPIO_CRL_CNF6;  GPIOA->CRL |= GPIO_CRL_CNF6_1;	
	GPIOA->CRL &= ~GPIO_CRL_CNF7;  GPIOA->CRL |= GPIO_CRL_CNF7_1;
	//GPIOA->CRH &= ~GPIO_CRH_CNF8;  GPIOA->CRH |= GPIO_CRH_CNF8_1;		
	GPIOA->CRH &= ~GPIO_CRH_CNF9;  GPIOA->CRH |= GPIO_CRH_CNF9_1;	
	GPIOA->CRH &= ~GPIO_CRH_CNF10; GPIOA->CRH |= GPIO_CRH_CNF10_0;	
	//GPIOA->CRH &= ~GPIO_CRH_CNF11; GPIOA->CRH |= GPIO_CRH_CNF11_1;	
	//GPIOA->CRH &= ~GPIO_CRH_CNF12; GPIOA->CRH |= GPIO_CRH_CNF12_1;	
	//GPIOA->CRH &= ~GPIO_CRH_CNF13; GPIOA->CRH |= GPIO_CRH_CNF13_1;	
	//GPIOA->CRH &= ~GPIO_CRH_CNF14; GPIOA->CRH |= GPIO_CRH_CNF14_1;	
	//GPIOA->CRH &= ~GPIO_CRH_CNF15; GPIOA->CRH |= GPIO_CRH_CNF15_1;	
	//*****GPIOB*****	
	GPIOB->CRL &= ~GPIO_CRL_CNF0;  GPIOB->CRL |= GPIO_CRL_CNF0_1;	
	GPIOB->CRL &= ~GPIO_CRL_CNF1;  GPIOB->CRL |= GPIO_CRL_CNF1_1;	
	GPIOB->CRL &= ~GPIO_CRL_CNF2;  GPIOB->CRL |= GPIO_CRL_CNF2_1;	
	//GPIOB->CRL &= ~GPIO_CRL_CNF3;  GPIOB->CRL |= GPIO_CRL_CNF3_1;	
	//GPIOB->CRL &= ~GPIO_CRL_CNF4;  GPIOB->CRL |= GPIO_CRL_CNF4_1;	
	//GPIOB->CRL &= ~GPIO_CRL_CNF5;  GPIOB->CRL |= GPIO_CRL_CNF5_1;	
	GPIOB->CRL &= ~GPIO_CRL_CNF6;  GPIOB->CRL |= GPIO_CRL_CNF6_1;	
	GPIOB->CRL &= ~GPIO_CRL_CNF7;  GPIOB->CRL |= GPIO_CRL_CNF7_1;
	//GPIOB->CRH &= ~GPIO_CRH_CNF8;  GPIOB->CRH |= GPIO_CRH_CNF8_1;		
	//GPIOB->CRH &= ~GPIO_CRH_CNF9;  GPIOB->CRH |= GPIO_CRH_CNF9_1;	
	//GPIOB->CRH &= ~GPIO_CRH_CNF10; GPIOB->CRH |= GPIO_CRH_CNF10_1;	
	//GPIOB->CRH &= ~GPIO_CRH_CNF11; GPIOB->CRH |= GPIO_CRH_CNF11_1;	
	//GPIOB->CRH &= ~GPIO_CRH_CNF12; GPIOB->CRH |= GPIO_CRH_CNF12_1;	
	//GPIOB->CRH &= ~GPIO_CRH_CNF13; GPIOB->CRH |= GPIO_CRH_CNF13_1;	
	//GPIOB->CRH &= ~GPIO_CRH_CNF14; GPIOB->CRH |= GPIO_CRH_CNF14_1;	
	//GPIOB->CRH &= ~GPIO_CRH_CNF15; GPIOB->CRH |= GPIO_CRH_CNF15_1;	
	//*****GPIOC*****
	//GPIOC->CRL &= ~GPIO_CRL_CNF0;  GPIOC->CRL |= GPIO_CRL_CNF0_1;	
	//GPIOC->CRL &= ~GPIO_CRL_CNF1;  GPIOC->CRL |= GPIO_CRL_CNF1_1;	
	//GPIOC->CRL &= ~GPIO_CRL_CNF2;  GPIOC->CRL |= GPIO_CRL_CNF2_1;	
	//GPIOC->CRL &= ~GPIO_CRL_CNF3;  GPIOC->CRL |= GPIO_CRL_CNF3_1;	
	//GPIOC->CRL &= ~GPIO_CRL_CNF4;  GPIOC->CRL |= GPIO_CRL_CNF4_1;	
	//GPIOC->CRL &= ~GPIO_CRL_CNF5;  GPIOC->CRL |= GPIO_CRL_CNF5_1;	
	//GPIOC->CRL &= ~GPIO_CRL_CNF6;  GPIOC->CRL |= GPIO_CRL_CNF6_1;	
	//GPIOC->CRL &= ~GPIO_CRL_CNF7;  GPIOC->CRL |= GPIO_CRL_CNF7_1;
	//GPIOC->CRH &= ~GPIO_CRH_CNF8;  GPIOC->CRH |= GPIO_CRH_CNF8_1;		
	//GPIOC->CRH &= ~GPIO_CRH_CNF9;  GPIOC->CRH |= GPIO_CRH_CNF9_1;	
	//GPIOC->CRH &= ~GPIO_CRH_CNF10; GPIOC->CRH |= GPIO_CRH_CNF10_1;	
	//GPIOC->CRH &= ~GPIO_CRH_CNF11; GPIOC->CRH |= GPIO_CRH_CNF11_1;	
	//GPIOC->CRH &= ~GPIO_CRH_CNF12; GPIOC->CRH |= GPIO_CRH_CNF12_1;	
	//GPIOC->CRH &= ~GPIO_CRH_CNF13; GPIOC->CRH |= GPIO_CRH_CNF13_1;	
	//GPIOC->CRH &= ~GPIO_CRH_CNF14; GPIOC->CRH |= GPIO_CRH_CNF14_1;	
	//GPIOC->CRH &= ~GPIO_CRH_CNF15; GPIOC->CRH |= GPIO_CRH_CNF15_1;	
	//*****GPIOD*****
	//GPIOD->CRL &= ~GPIO_CRL_CNF0;  GPIOD->CRL |= GPIO_CRL_CNF0_1;	
	//GPIOD->CRL &= ~GPIO_CRL_CNF1;  GPIOD->CRL |= GPIO_CRL_CNF1_1;	
	//GPIOD->CRL &= ~GPIO_CRL_CNF2;  GPIOD->CRL |= GPIO_CRL_CNF2_1;	
	//GPIOD->CRL &= ~GPIO_CRL_CNF3;  GPIOD->CRL |= GPIO_CRL_CNF3_1;	
	//GPIOD->CRL &= ~GPIO_CRL_CNF4;  GPIOD->CRL |= GPIO_CRL_CNF4_1;	
	//GPIOD->CRL &= ~GPIO_CRL_CNF5;  GPIOD->CRL |= GPIO_CRL_CNF5_1;	
	//GPIOD->CRL &= ~GPIO_CRL_CNF6;  GPIOD->CRL |= GPIO_CRL_CNF6_1;	
	//GPIOD->CRL &= ~GPIO_CRL_CNF7;  GPIOD->CRL |= GPIO_CRL_CNF7_1;
	//GPIOD->CRH &= ~GPIO_CRH_CNF8;  GPIOD->CRH |= GPIO_CRH_CNF8_1;		
	//GPIOD->CRH &= ~GPIO_CRH_CNF9;  GPIOD->CRH |= GPIO_CRH_CNF9_1;	
	//GPIOD->CRH &= ~GPIO_CRH_CNF10; GPIOD->CRH |= GPIO_CRH_CNF10_1;	
	//GPIOD->CRH &= ~GPIO_CRH_CNF11; GPIOD->CRH |= GPIO_CRH_CNF11_1;	
	//GPIOD->CRH &= ~GPIO_CRH_CNF12; GPIOD->CRH |= GPIO_CRH_CNF12_1;	
	//GPIOD->CRH &= ~GPIO_CRH_CNF13; GPIOD->CRH |= GPIO_CRH_CNF13_1;	
	//GPIOD->CRH &= ~GPIO_CRH_CNF14; GPIOD->CRH |= GPIO_CRH_CNF14_1;	
	//GPIOD->CRH &= ~GPIO_CRH_CNF15; GPIOD->CRH |= GPIO_CRH_CNF15_1;	
	//Uncomment the following to set the pin to 11: (reserved        | af open-drain) 
	//*****GPIOA*****
	//GPIOA->CRL |= GPIO_CRL_CNF0;
	//GPIOA->CRL |= GPIO_CRL_CNF1;
	//GPIOA->CRL |= GPIO_CRL_CNF2;
	//GPIOA->CRL |= GPIO_CRL_CNF3;
	//GPIOA->CRL |= GPIO_CRL_CNF4;
	//GPIOA->CRL |= GPIO_CRL_CNF5;
	//GPIOA->CRL |= GPIO_CRL_CNF6;
	//GPIOA->CRL |= GPIO_CRL_CNF7;
	//GPIOA->CRH |= GPIO_CRH_CNF8;
	//GPIOA->CRH |= GPIO_CRH_CNF9;
	//GPIOA->CRH |= GPIO_CRH_CNF10;
	//GPIOA->CRH |= GPIO_CRH_CNF11;
	//GPIOA->CRH |= GPIO_CRH_CNF12;
	//GPIOA->CRH |= GPIO_CRH_CNF13;
	//GPIOA->CRH |= GPIO_CRH_CNF14;
	//GPIOA->CRH |= GPIO_CRH_CNF15;
	//*****GPIOB*****
	//GPIOB->CRL |= GPIO_CRL_CNF0;
	//GPIOB->CRL |= GPIO_CRL_CNF1;
	//GPIOB->CRL |= GPIO_CRL_CNF2;
	//GPIOB->CRL |= GPIO_CRL_CNF3;
	//GPIOB->CRL |= GPIO_CRL_CNF4;
	//GPIOB->CRL |= GPIO_CRL_CNF5;
	//GPIOB->CRL |= GPIO_CRL_CNF6;
	//GPIOB->CRL |= GPIO_CRL_CNF7;
	//GPIOB->CRH |= GPIO_CRH_CNF8;
	//GPIOB->CRH |= GPIO_CRH_CNF9;
	//GPIOB->CRH |= GPIO_CRH_CNF10;
	//GPIOB->CRH |= GPIO_CRH_CNF11;
	//GPIOB->CRH |= GPIO_CRH_CNF12;
	//GPIOB->CRH |= GPIO_CRH_CNF13;
	//GPIOB->CRH |= GPIO_CRH_CNF14;
	//GPIOB->CRH |= GPIO_CRH_CNF15;
	//*****GPIOC*****
	//GPIOC->CRL |= GPIO_CRL_CNF0;
	//GPIOC->CRL |= GPIO_CRL_CNF1;
	//GPIOC->CRL |= GPIO_CRL_CNF2;
	//GPIOC->CRL |= GPIO_CRL_CNF3;
	//GPIOC->CRL |= GPIO_CRL_CNF4;
	//GPIOC->CRL |= GPIO_CRL_CNF5;
	//GPIOC->CRL |= GPIO_CRL_CNF6;
	//GPIOC->CRL |= GPIO_CRL_CNF7;
	//GPIOC->CRH |= GPIO_CRH_CNF8;
	//GPIOC->CRH |= GPIO_CRH_CNF9;
	//GPIOC->CRH |= GPIO_CRH_CNF10;
	//GPIOC->CRH |= GPIO_CRH_CNF11;
	//GPIOC->CRH |= GPIO_CRH_CNF12;
	//GPIOC->CRH |= GPIO_CRH_CNF13;
	//GPIOC->CRH |= GPIO_CRH_CNF14;
	//GPIOC->CRH |= GPIO_CRH_CNF15;
	//*****GPIOD*****
	//GPIOD->CRL |= GPIO_CRL_CNF0;
	//GPIOD->CRL |= GPIO_CRL_CNF1;
	//GPIOD->CRL |= GPIO_CRL_CNF2;
	//GPIOD->CRL |= GPIO_CRL_CNF3;
	//GPIOD->CRL |= GPIO_CRL_CNF4;
	//GPIOD->CRL |= GPIO_CRL_CNF5;
	//GPIOD->CRL |= GPIO_CRL_CNF6;
	//GPIOD->CRL |= GPIO_CRL_CNF7;
	//GPIOD->CRH |= GPIO_CRH_CNF8;
	//GPIOD->CRH |= GPIO_CRH_CNF9;
	//GPIOD->CRH |= GPIO_CRH_CNF10;
	//GPIOD->CRH |= GPIO_CRH_CNF11;
	//GPIOD->CRH |= GPIO_CRH_CNF12;
	//GPIOD->CRH |= GPIO_CRH_CNF13;
	//GPIOD->CRH |= GPIO_CRH_CNF14;
	//GPIOD->CRH |= GPIO_CRH_CNF15;
}

bool readPin(GPIO_TypeDef* gpio, int pin){ //(GPIOX, X(0-15))
	return gpio->IDR & (0x0001 << pin);
}

void setPin(GPIO_TypeDef* gpio, int pin, bool enable){ //(GPIOX, X(0-15), enable)
	gpio->BSRR |= 0x0001 << (enable ? pin : pin+16);
}

uint8_t read4Bits(void){ //reads GPIOB 6,10,4,5 in that order and returns a uint8_t with those bits set to the corrisponding pins
	uint8_t val = 0;
	
	val += (readPin(GPIOB,  6) ? (0x1<<0) : 0);
	val += (readPin(GPIOB, 10) ? (0x1<<1) : 0);
	val += (readPin(GPIOB,  4) ? (0x1<<2) : 0);
	val += (readPin(GPIOB,  5) ? (0x1<<3) : 0);
	
	return val;
}

void invertPin(GPIO_TypeDef* gpio, int pin){ //(GPIOX, X(0-15))
	gpio->ODR ^= (0x1 << pin);
}
